<<<<<<< HEAD
title : deepcrunch
=======
title : DeepCrunch
>>>>>>> e186a2bf6352f56247cb540ee0490ed5f1f23add
description: 'Deep Crunch Awesome Blog'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
